//
//  Model.swift
//  FootballApps
//
//  Created by Putilov Nikita on 31.07.2024.
//

import Foundation

struct TeamModel {
    let image: String
    let name: String
    let star: Int
}

struct TeamViewModel {
    static let teamModel = [TeamModel(image: "Manchester city", name: "Machester city", star: 5),
                            TeamModel(image: "Real Madrid", name: "Real Madrid", star: 5),
                            TeamModel(image: "Lyon", name: "Olympique Lyonnais", star: 5),
                            TeamModel(image: "PSG", name: "Paris Saint-Germain", star: 5),
                            TeamModel(image: "Barcelona", name: "Barcelona", star: 5),
                            TeamModel(image: "Vfl Wolfsburg", name: "Vfl Wolfsburg", star: 5),
                            TeamModel(image: "Atletico", name: "Atletico de Madrid", star: 5),
                            TeamModel(image: "Liverpool", name: "Liverpool", star: 5),
                            TeamModel(image: "Inter", name: "Inter", star: 45),
                            TeamModel(image: "MU", name: "Manchester United", star: 45),
                            TeamModel(image: "Tottenham", name: "Tottenham Hotspur", star: 45),
                            TeamModel(image: "Borussia Dortmund", name: "Borussia Dortmund", star: 45),
                            TeamModel(image: "Napoli", name: "Napoli", star: 45),
                            TeamModel(image: "Juventus", name: "Juventus", star: 45),
                            TeamModel(image: "Newcastle", name: "Newcastle United", star: 45),
                            TeamModel(image: "Milan", name: "Milan", star: 45),
                            TeamModel(image: "RB Leipzig", name: "RB Leipzig", star: 45),
                            TeamModel(image: "Roma", name: "Roma", star: 45),
                            TeamModel(image: "Sevilla FC", name: "Sevilla FC", star: 45),
                            TeamModel(image: "Lazio", name: "Lazio", star: 45),
                            TeamModel(image: "Bayer 04 Leverkusen", name: "Bayer 04 Leverkusen", star: 45),
                            TeamModel(image: "Real Betis", name: "Real Betis Balompié", star: 45),
                            TeamModel(image: "Real Sociedad", name: "Real Sociedad", star: 45),
                            TeamModel(image: "Aston Villa", name: "Aston Villa", star: 45),
                            TeamModel(image: "Villarreal CF", name: "Villarreal CF", star: 45),
                            TeamModel(image: "Athletic", name: "Athletic Club de Bilbao", star: 45),
                            TeamModel(image: "Galatasaray", name: "Galatasaray", star: 4),
                            TeamModel(image: "Atalanta", name: "Atalanta", star: 4),
                            TeamModel(image: "FC Porto", name: "FC Porto", star: 4),
                            TeamModel(image: "Benfica", name: "Benfica", star: 4),
                            TeamModel(image: "Fiorentina", name: "Fiorentina", star: 4),
                            TeamModel(image: "Marseille", name: "Olympique de Marseille", star: 4),
                            TeamModel(image: "West Ham", name: "West Ham United", star: 4),
                            TeamModel(image: "Everton", name: "Everton", star: 4),
                            TeamModel(image: "Frankfurt", name: "Eintracht Frankfurt", star: 4),
                            TeamModel(image: "Wolverhampton", name: "Wolverhampton Wanderers", star: 4),
                            TeamModel(image: "Sporting", name: "Sporting CP", star: 4),
                            TeamModel(image: "Braga", name: "Braga", star: 4),
                            TeamModel(image: "Stade Rennais", name: "Stade Rennais", star: 4),
                            TeamModel(image: "CA Osasuna", name: "CA Osasuna", star: 4),
                            TeamModel(image: "Fulham", name: "Fulham", star: 4),
                            TeamModel(image: "Brighton", name: "Brighton & Hove Albion", star: 4),
                            TeamModel(image: "Brentford", name: "Brentford", star: 4),
                            TeamModel(image: "Al Ittihad", name: "Al Ittihad", star: 4),
                            TeamModel(image: "AS Monaco", name: "AS Monaco", star: 4),
                            TeamModel(image: "Ajax", name: "Ajax", star: 4),
                            TeamModel(image: "Hoffenheim", name: "TSG 1899 Hoffenheim", star: 4),
                            TeamModel(image: "Palmeiras", name: "Palmeiras", star: 4),
                            TeamModel(image: "Fenerbahce", name: "Fenerbahçe", star: 4),
                            TeamModel(image: "Celta", name: "RC Celta de Vigo", star: 4),
                            TeamModel(image: "Rayo Vallecano", name: "Rayo Vallecano", star: 4),
                            TeamModel(image: "OGC Nice", name: "OGC Nice", star: 4),
                            TeamModel(image: "Flamengo", name: "Flamengo", star: 4),
                            TeamModel(image: "SC Freiburg", name: "SC Freiburg", star: 4),
                            TeamModel(image: "Getafe CF", name: "Getafe CF", star: 4),
                            TeamModel(image: "FC Union Berlin", name: "FC Union Berlin", star: 4),
                            TeamModel(image: "Nottingham Forest", name: "Nottingham Forest", star: 4),
                            TeamModel(image: "LOSC Lille", name: "LOSC Lille", star: 4),
                            TeamModel(image: "PSV", name: "PSV", star: 4),
                            TeamModel(image: "River Plate", name: "River Plate", star: 4),
                            TeamModel(image: "RC Lens", name: "RC Lens", star: 4),
                            TeamModel(image: "Girona FC", name: "Girona FC", star: 4),
                            TeamModel(image: "Crystal Palace", name: "Crystal Palace", star: 4),
                            TeamModel(image: "Borussia M'gladbach", name: "Borussia M'gladbach", star: 4),
                            TeamModel(image: "Leicester City", name: "Leicester City", star: 4),
                            TeamModel(image: "Al Nassr", name: "Al Nassr", star: 4),
                            TeamModel(image: "Bologna", name: "Bologna", star: 4),
                            TeamModel(image: "Sassuolo", name: "Sassuolo", star: 4),
                            TeamModel(image: "Atlético Mineiro", name: "Atlético Mineiro", star: 4),
                            TeamModel(image: "RCD Mallorca", name: "RCD Mallorca", star: 4),
                            TeamModel(image: "AC Monza", name: "AC Monza", star: 4),
                            TeamModel(image: "Mainz", name: "FSV Mainz 05", star: 4),
                            TeamModel(image: "AEK", name: "AEK", star: 4),
                            TeamModel(image: "Torino", name: "Torino", star: 4),
                            TeamModel(image: "Boca Juniors", name: "Boca Juniors", star: 4),
                            TeamModel(image: "RCD Espanyol", name: "RCD Espanyol", star: 4),
                            TeamModel(image: "UD Almería", name: "UD Almería", star: 4),
                            TeamModel(image: "Cádiz CF", name: "Cádiz CF", star: 4),
                            TeamModel(image: "Valencia CF", name: "Valencia CF", star: 4),
                            TeamModel(image: "Feyenoord", name: "Feyenoord", star: 4),
                            TeamModel(image: "Al Hilal", name: "Al Hilal", star: 4),
    ]
}
